# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'DispatchSemaphore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DispatchSemaphore
  pod 'AFNetworking', '~> 3.1.0'

  target 'DispatchSemaphoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DispatchSemaphoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
